# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 970acc59ef7ef9786cc618b896c801a277a65808ab870853b86effc09b4a7a35bb18b668f99e9f0c3272a68f7267ba68e532bb2193ee408b04aecff29efc4bfd

test:
  secret_key_base: a072c905a9782617e5d4d7357ce16280cadfbfa5bb2d763fbd1eac84cb0e4b478df7dfa838b3cb60a71589f798855346e24fd4743e9fef8dc952a4300adafc3e

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
